#!@bash@/bin/bash

set -o errexit
set -o nounset

echo;
echo "generating album";
echo;

@generator@/bin/elbum "$@";

echo;
echo;
echo "album generation complete";
echo;
echo "configuring website";
echo;

dest=$2;
cd "$dest";

nix-store --add-root elbum --indirect -r @client@ > /dev/null;

for f in index.html elbum.js .htaccess; do
    if [ -a $f ]; then
        echo "leaving existing $f ->" $(readlink -e $f) "rather than replacing with a link to @client@/$f";
    else
        ln -s elbum/$f;
    fi
done

echo;
echo "website configuration complete";
echo;
