#!@bash@/bin/bash

set -o errexit
set -o nounset

@generator@/bin/elbum "$@";

dest=$2;
cd $dest;

nix-store --add-root elbum --indirect -r @client@ > /dev/null;

for f in index.html elbum.js .htaccess; do
    if [ -a $f ]; then
        echo "leaving existing $f ->" $(readlink -e $f) "rather than replacing with a link to @client@/$f";
    else
        ln -s elbum/$f;
    fi
done
