#!@bash@/bin/bash

set -o errexit
set -o nounset

@generator@/bin/elbum "$@";

dest=$2;
cd $dest;

nix-store --add-root elbum --indirect -r @client@ > /dev/null;

ln -s elbum/index.html;
ln -s elbum/elbum.js;
ln -s elbum/.htaccess;
