name: "Nix Checks"
on:
  pull_request:
  push:
    branches:
      - "dev"
jobs:
  build:
    name: nix-build can build the project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: |
          nix-build
          nix-store --export $(nix-store --query --requisites result) > elbum.nar
      - uses: actions/upload-artifact@v4
        with:
          name: elbum.nar
          path: elbum.nar
  shell:
    name: nix-shell can produce a working shell environment
    runs-on: ubuntu-latest
    env:
      # lamdera is unfree
      NIXPKGS_ALLOW_UNFREE: 1
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix-shell --run true
